### ISSUE TITLE
Security update: Drupal 7.95

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/byzantine_translations#30]
Release notes: https://www.drupal.org/project/drupal/releases/7.95
Our upgrade instructions: https://github.com/pulibrary/pul_library_drupal/wiki/How-to-upgrade-Drupal-core and https://github.com/pulibrary/byzantine_translations/wiki/Upgrade-Drupal-Core

**Comment by kevinreiss** [comment]
deployed to production
